 const oquvchilar = [
    "MOXIRBEK ABDUMALIKOV MUZAFFAR O'G'LI", 
    "HUMOYUN ABDUQODIROV G'AYRAT O'G'LI",
    "AZIZJON ALIQULOV IKROMJON O'G'LI", 
    "ZAFAR IBROHIMOV IKROM O'G'LI", 
    "MIRKOMIL MIRXOMIDOV ILXOM O'G'LI",
    "OYATILLO OBLOBERDIYEV OYBEK O'G'LI", 
    "IBROHIM QAXROMONOV MUROD O'G'LI", 
    "JAHONGIR XALIMJONOV QAXRAMON O'G'LI", 
    "AZAMAT SA'DULLAYEV KAHRAMON O'G'LI",
    "FAZLIDDIN USMONOV AXLIDDIN O'G'LI", 
    "SHAXZODBEK SHAVKATOV SHUXRATBEK O'G'LI",
    "ABDURASHID ABDURAXMONOV RAVSHAN O'G'LI", 
    "SHAXZODBEK SODIQJONOV SHOYATBEK O'G'LI", 
    "ISLOMBEK KAMOLIDDINOV SAYFIDDIN O'G'LI",
    "OZODBEK NEMATOV BOTIRALIJONOVICH", 
    "RUSLAN TODJIDINOV RUKNIDDIN O'G'LI", 
    "TOHIRJON YUSUPOV BOTIRALI O'G'LI", 
    "MEHRIDDIN BARNAYEV SHONAZAR O'G'LI",
    "UMIDJON HAMIDJONOV ZARIFJONOVICH", 
    "AXMADBEK USMONOV ANVAR O'G'LI", 
    "SAID ORIFOV ODIL O'G'LI", 
    "SHOHAKBAR ANVARJONOV", 
    "SARDOR ERKINOV DILSHOD O'G'LI", 
    "SHOXRUZBEK ABDURAXMONOV AZIZBEK O'G'LI"
];

 document.getElementById("tanlashBtn").addEventListener("click", function() {
     const tasodifiyIndex = Math.floor(Math.random() * oquvchilar.length);
    const tanlanganOquvchi = oquvchilar[tasodifiyIndex];

     document.getElementById("natija").innerText = "📖 " + tanlanganOquvchi;
});
